modLoader="javafml"

loaderVersion="[36,)"

license="All rights reserved"

issueTrackerURL="https://github.com/chandler05/dangers/issues"

[[mods]]

modId="chandlers_dangers"

version="1.0"

displayName="Dangers"

logoFile="examplemod.png"

credits="Bosses inspired by the Capcom game Zack and Wiki"

authors="Chandler"

description='''
A mod that adds challenging bosses and enemies to the game.
'''

[[dependencies.examplemod]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
